# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/grandprimeve3g/setup-makefiles.sh

PROPRIETARY_FILES := \
	etc/wifi/wpa_supplicant_overlay.conf \
    etc/wifi/wpa_supplicant.conf \
    etc/wifi/p2p_supplicant_overlay.conf \
    etc/wifi/nvram_net.txt \
    lib/libisp.so \
    lib/libmorpho_easy_hdr.so \
    lib/libcalibration.so \
    lib/libAF.so \
    lib/libsft_af_ctrl.so \
    lib/libdeflicker.so \
    lib/libynoise.so \
    lib/libspaf.so \
    lib/liblsc.so \
    lib/libAl_Awb.so \
    lib/libAl_Awb_Sp.so \
    lib/libae.so \
    lib/libawb.so \
	lib/egl/libGLES_mali.so \
    lib/hw/camera.sc8830.so \
    lib/hw/sensors.sc8830.so \
    lib/hw/keystore.default.so \
    lib/hw/lights.sc8830.so \
    lib/hw/vibrator.default.so \
    lib/hw/gralloc.sc8830.so \
	lib/hw/hwcomposer.sc8830.so \
	lib/hw/sprd_gsp.sc8830.so \
	lib/modules/autotst.ko \
	lib/modules/gator.ko \
	lib/modules/mali.ko \
	lib/modules/mmc_test.ko \
	lib/modules/pskey_bt.txt \
	lib/modules/sprdwl.ko \
	lib/modules/trout_fm.ko \
    lib/libyasalgo.so \
	usr/idc/msg22xx.idc \
	vendor/firmware/BCM4343A0_001.001.034.0056.0197_M_ORC_Core3.hcd \
	vendor/firmware/fw_bcmdhd.bin \
	vendor/firmware/fw_bcmdhd_apsta.bin \
	vendor/firmware/vbc_eq \
	vendor/lib/mediadrm/libdrmclearkeyplugin.so \
	vendor/lib/libavcodec.so \
	vendor/lib/libavformat.so \
	vendor/lib/libavutil.so \
	vendor/lib/libbt-vendor.so \
	vendor/lib/libffmpeg_extractor.so \
	vendor/lib/libffmpeg_omx.so \
	vendor/lib/libffmpeg_utils.so \
	vendor/lib/libswresample.so \
	vendor/lib/libswscale.so \
	vendor/vandroids4ptx/efs.img 
PRODUCT_COPY_FILES += \
    $(foreach f,$(PROPRIETARY_FILES),vendor/samsung/grandprimeve3g/proprietary/$(f):system/$(f))
